config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'homes#top'
post 'books' => 'books#create'
get 'books/:id' => 'books#show', as: 'book'
get 'books/:id/edit' => 'books#edit', as: 'edit_book'
get 'books' => 'books#index'
patch 'books/:id' => 'books#update', as: 'update_book'
delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])

  end
  def create
    @books = Book.all
    @book = Book.new(book_params)

    if @book.save
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      render :index
    end

  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book),notice: 'Book was successfully updated.'
    else
      render :edit
    end

  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path

  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<div class="main">
 <h1>Editing Book</h1>

 <% if @book.errors.any? %>
  <div class="error">

     <div class="error-top"> <%= @book.errors.count %>errors prohibited this book from being saved:</div>
     <ul class="error-message">
       <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
       <% end %>
     </ul>

   </div>
 <% end %>

 <div>
  <div class="submit-box">
    <%= form_with model:@book, url: update_book_path, local:true do |f| %>
       <div class="field">
        <% if @book.errors.any? %>
          <div class="field-error">Title</div>
          <div class="field-error"><%= f.text_field :title %></div>
        <% else %>
          <div class="field-ok">Title</div>
          <div class="field-ok"><%= f.text_field :title %></div>
        <% end %>
       </div>
       <div class="field">
        <% if @book.errors.any? %>
          <div class="field-error">Body</div>
          <div class="field-error"><%= f.text_area :body %></div>
        <% else %>
          <div class="field-ok">Body</div>
          <div class="field-ok"><%= f.text_area :body %></div>
        <%end %>
       </div>
       <span class="submit-bottom"><%= f.submit 'Update Book' %></span>
    <% end %>
  </div>
  <div class="bottom">
    <span class="bottom-c"><%= link_to "Show", book_path(@book.id) %></span>
    |
    <span class="bottom-c"><%= link_to "Back", books_path %></span>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<div class="main">
 <h1>Books</h1>
 <table boder="1">
  <thead>
   <tr>
    <th class="book-title">Title</th>
    <th class="book-body">Body</th>
    <th></th>
   </tr>
  </thead>

  <tbody>
   <% @books.each do |book| %>
   <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to "Show", book_path(book) %></td>
    <td><%= link_to "Edit", edit_book_path(book) %></td>
    <td><%= link_to "Destroy", book_path(book), method: :delete %></td>
   </tr>
    <% end %>
  </tbody>


 </table>



  <% if @book.errors.any? %>
   <div class="error">
     <div class="error-top"><%= @book.errors.count %>errors prohibited this book from being saved:</div>
     <ul class="error-message">
           <% @book.errors.full_messages.each do |message| %>
             <li><%= message %></li>
           <% end %>
     </ul>

   </div>
  <% end %>

  <div class="index-new">
   <h2>New book</h2>
   <div class="submit-box">
     <%= form_with model:@book, url:'/books', local:true do |f| %>
       <div class="field">
        <% if @book.errors.any? %>
          <div class="field-error">Title</div>
          <div class="field-error"><%= f.text_field :title %></div>
        <% else %>
          <div class="field-ok">Title</div>
          <div class="field-ok"><%= f.text_field :title %></div>
        <% end %>

       </div>
       <div class="field">
        <% if @book.errors.any? %>
          <div class="field-error">Body</div>
          <div class="field-error"><%= f.text_area :body %></div>
        <% else %>
          <div class="field-ok">Body</div>
          <div class="field-ok"><%= f.text_area :body %></div>
        <%end %>

       </div>
       <span class="submit-bottom"> <%= f.submit 'Create Book' %></span>
     <% end %>
   </div>
  </div>

</div>

app/views/books/show.html.erb
<div class="main">
  <p id="notice"><%= flash[:notice] %></p>
  <p>
    <strong>title:</strong>
    <%= @book.title %>
  </p>
  <p>
    <strong>body:</strong>
    <%= @book.body %>
  </p>

 <div class="bottom">
  <span class="bottom-c"><%= link_to "Edit", edit_book_path(@book.id) %></span>
  |
  <span class="bottom-c"><%= link_to "Back", books_path %></span>
 </div>
</div>

app/views/homes/top.html.erb
<div class="main">
  <h1 class="top-heading">ようこそBookersへ！</h1>
  <p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>
  <p>印象を交換することができます</p>
  <p><%= link_to "start", books_path %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>